Repository graasp/graasp-query-client, pull requests merged in 2021-08, with the labels that each got.

#50 refactor: integrate ws hooks into api hooks
  babel.config.js
  src/hooks/chat.ts
  src/hooks/index.ts
  src/hooks/item.ts
  src/queryClient.ts
  src/ws/hooks/chat.ts
  src/ws/hooks/index.ts
  src/ws/hooks/item.ts
  src/ws/hooks/membership.ts
  src/ws/index.ts
  src/ws/ws-client.ts
Labels: feature, priority

#53 fix: trim items names on add and edit
  src/api/item.ts
  src/mutations/item.ts
Labels: bug

#55 fix: disable ws updates for useChildren if enabled option set to false
  src/hooks/item.ts
Labels: bug

#58 18/hooks tests
  package.json
  src/api/routes.ts
  src/config/keys.ts
  src/hooks/chat.test.ts
  src/hooks/itemFlag.test.ts
  src/hooks/itemFlag.ts
  src/hooks/itemTag.test.ts
  src/hooks/itemTag.ts
  src/mutations/item.test.ts
  src/mutations/item.ts
  test/constants.ts
Labels: test

#63 fix: remove cookie when logout is confirmed, prevents logout loop
  src/mutations/member.ts
Labels: bug

#65 fix: ensures the email is always sent in lowercase
  src/api/routes.ts
Labels: bug

#62 Update GetMemberBy Route
  src/api/routes.ts
Labels: chore
