Repository graasp/graasp-query-client, pull requests merged in 2023-09, with the labels that each got.

#420 feat: expose url parameter for auth redirection
  src/api/authentication.ts
  src/mutations/authentication.ts
Labels: feature

#424 feat: add etherpad fetch queue
  src/api/etherpad.ts
  src/api/index.ts
  src/api/item.ts
Labels: bug :beetle:, feature

#430 fix: convert date string in websocket data
  .eslintrc
  babel.config.cjs
  commitlint.config.cjs
  jest.config.ts
  package.json
  src/api/action.ts
  src/api/itemTag.ts
  src/hooks/action.test.ts
  src/hooks/action.ts
  src/hooks/apps.test.ts
  src/hooks/category.test.ts
  src/hooks/chat.test.ts
  src/hooks/invitation.test.ts
  src/hooks/item.test.ts
  src/hooks/itemFavorite.test.ts
  src/hooks/itemFlag.test.ts
  src/hooks/itemLike.test.ts
  src/hooks/itemTag.test.ts
  src/hooks/itemTag.ts
  src/hooks/itemValidation.test.ts
  src/hooks/member.test.ts
  src/hooks/membership.test.ts
  src/hooks/mention.test.ts
  src/hooks/mention.ts
  src/hooks/search.test.ts
  src/hooks/search.ts
  src/mutations/authentication.test.ts
  src/mutations/authentication.ts
  src/mutations/chat.test.ts
  src/mutations/invitation.test.ts
  src/mutations/item.test.ts
  src/mutations/item.ts
  src/mutations/itemFlag.test.ts
  src/mutations/itemLike.test.ts
  src/mutations/itemLogin.test.ts
  src/mutations/itemTag.test.ts
  src/mutations/itemTag.ts
  src/mutations/member.test.ts
  src/mutations/membership.test.ts
  src/mutations/mention.test.ts
  src/ws/hooks/item.test.ts
  src/ws/hooks/item.ts
  src/ws/hooks/membership.test.ts
  src/ws/hooks/mentions.test.ts
  test/constants.ts
  test/resolver.cjs
  test/setupTests.ts
  test/setupTestsAfterEnv.ts
  test/utils.tsx
  tsconfig.json
  tsconfig.test.json
  yarn.lock
Labels: bug :beetle:

#441 fix: webpack import error
  example/README.md
  example/package.json
  example/public/favicon.ico
  example/public/index.html
  example/public/manifest.json
  example/src/App.tsx
  example/src/configureQueryClient.ts
  example/src/index.tsx
  example/src/setupTests.ts
  example/tsconfig.json
  jest.config.ts
  package.json
  src/mutations/action.test.ts
  src/mutations/authentication.test.ts
  src/mutations/chat.test.ts
  src/mutations/invitation.test.ts
  src/mutations/item.test.ts
  src/mutations/itemFavorite.test.ts
  src/mutations/member.test.ts
  src/mutations/mention.test.ts
  src/queryClient.ts
  test/utils.tsx
  test/wsUtils.tsx
  tsconfig.json
  yarn.lock
Labels: bug :beetle:, build

#450 fix: use limit and offset
  src/api/search.ts
  src/config/keys.ts
  src/hooks/search.test.ts
  src/hooks/search.ts
Labels: improvement

#455 fix(type): allow description in editItem input type
  src/mutations/item.ts
Labels: chore
