Repository graasp/graasp-query-client, pull requests merged in 2023-03, with the labels that each got.

#245 244 fix add currentmemberid back to signout mutation
  package.json
  src/api/category.ts
  src/api/chat.ts
  src/hooks/item.ts
  src/mutations/authentication.ts
  src/mutations/chat.ts
  src/utils/util.ts
  yarn.lock
Labels: bug, chore, documentation

#248 fix: catch avatar not found error
  src/hooks/member.test.ts
  src/hooks/member.ts
  test/constants.ts
Labels: bug, improvement

#250 fix: allow optional properties
  src/api/apps.ts
  src/api/itemLogin.ts
  src/mutations/itemLogin.ts
Labels: bug

#252 fix: use ThumbnailSize from sdk
  package.json
  src/config/constants.ts
  src/hooks/item.test.ts
  src/hooks/member.test.ts
  src/mutations/item.test.ts
  src/mutations/item.ts
  src/mutations/member.test.ts
  src/mutations/member.ts
  tsconfig.test.json
  yarn.lock
Labels: bug, improvement

#254 fix(type): of useTags hook
  src/hooks/itemTag.ts
Labels: bug

#258 feat: bump @graasp/sdk
  package.json
  yarn.lock
Labels: dependencies

#263 fix: bump sdk to 0.10.0
  package.json
  yarn.lock
Labels: chore
