Repository graasp/graasp-query-client, pull requests merged in 2023-07, with the labels that each got.

#337 fix: export public getAllPublishedItems route
  package.json
  src/api/routes.ts
  yarn.lock
Labels: bug :beetle:, chore

#333 feat: add mobile auth queries
  .github/workflows/test.yml
  src/api/authentication.ts
  src/api/axios.ts
  src/api/routes.ts
  src/mutations/authentication.ts
  src/mutations/invitation.ts
  src/mutations/item.test.ts
  src/mutations/item.ts
  src/mutations/itemTag.ts
  src/mutations/member.ts
  src/mutations/membership.test.ts
  src/mutations/membership.ts
  src/types.ts
  src/ws/hooks/item.ts
  test/constants.ts
  test/utils.tsx
  tsconfig.test.json
Labels: feature

#351 fix: use delete instead of post for unpublish
  src/api/itemPublish.ts
Labels: bug :beetle:

#357 feat: add most liked and most recent collections
  src/api/itemPublish.ts
  src/api/routes.ts
  src/config/keys.ts
  src/hooks/itemPublish.ts
Labels: feature

#354 feat: add mobile sign up hooks
  src/api/authentication.ts
  src/api/routes.ts
  src/mutations/authentication.test.ts
  src/mutations/authentication.ts
Labels: improvement
