Repository graasp/graasp-query-client, pull requests merged in 2024-02, with the labels that each got.

#607 feat: add types filter in useAccessible
  src/api/routes.ts
  src/hooks/item.test.ts
Labels: feature

#611 feat: allow useChildren to filter by types
  src/api/item.ts
  src/api/routes.ts
  src/config/keys.ts
  src/hooks/item.test.ts
  src/hooks/item.ts
Labels: feature

#613 fix: allow undefined memberId in publicprofile hook
  src/config/keys.ts
  src/hooks/publicProfile.ts
  src/ws/hooks/item.ts
Labels: chore

#636 fix: adapt return type of item publish info
  src/api/itemPublish.ts
Labels: improvement

#641 fix: make graasp deps peer
  package.json
  yarn.lock
Labels: build, dependencies

#617 refactor: change item keys
  src/config/keys.ts
  src/hooks/category.test.ts
  src/hooks/category.ts
  src/hooks/item.test.ts
  src/hooks/item.ts
  src/hooks/itemFavorite.test.ts
  src/hooks/itemFavorite.ts
  src/hooks/itemGeolocation.test.ts
  src/hooks/itemGeolocation.ts
  src/hooks/itemLike.test.ts
  src/hooks/itemLike.ts
  src/hooks/itemLogin.ts
  src/hooks/itemPublish.ts
  src/hooks/itemTag.test.ts
  src/hooks/itemTag.ts
  src/hooks/itemValidation.test.ts
  src/hooks/itemValidation.ts
  src/hooks/member.test.ts
  src/hooks/member.ts
  src/hooks/plan.ts
  src/hooks/publicProfile.test.ts
  src/hooks/publicProfile.ts
  src/hooks/search.test.ts
  src/hooks/search.ts
  src/hooks/shortLink.ts
  src/mutations/authentication.test.ts
  src/mutations/authentication.ts
  src/mutations/item.test.ts
  src/mutations/item.ts
  src/mutations/itemCategory.test.ts
  src/mutations/itemCategory.ts
  src/mutations/itemFavorite.test.ts
  src/mutations/itemFavorite.ts
  src/mutations/itemFlag.test.ts
  src/mutations/itemFlag.ts
  src/mutations/itemGeolocation.test.ts
  src/mutations/itemGeolocation.ts
  src/mutations/itemLike.test.ts
  src/mutations/itemLike.ts
  src/mutations/itemLogin.test.ts
  src/mutations/itemLogin.ts
  src/mutations/itemPublish.test.ts
  src/mutations/itemPublish.ts
  src/mutations/itemTag.test.ts
  src/mutations/itemTag.ts
  src/mutations/itemValidation.test.ts
  src/mutations/itemValidation.ts
  src/mutations/member.test.ts
  src/mutations/member.ts
  src/mutations/membership.test.ts
  src/mutations/plan.ts
  src/mutations/publicProfile.test.ts
  src/mutations/shortLink.ts
  src/ws/hooks/item.test.ts
  src/ws/hooks/item.ts
Labels: refactor

#657 fix: move to query v4
  .husky/pre-push
  package.json
  src/hooks/action.ts
  src/hooks/apps.ts
  src/hooks/category.ts
  src/hooks/chat.ts
  src/hooks/etherpad.ts
  src/hooks/invitation.ts
  src/hooks/item.ts
  src/hooks/itemFavorite.ts
  src/hooks/itemGeolocation.ts
  src/hooks/itemLike.ts
  src/hooks/itemLogin.ts
  src/hooks/itemPublish.ts
  src/hooks/itemTag.ts
  src/hooks/itemValidation.ts
  src/hooks/member.ts
  src/hooks/membership.ts
  src/hooks/mention.ts
  src/hooks/publicProfile.ts
  src/hooks/search.ts
  src/hooks/shortLink.ts
  src/hooks/subscription.ts
  src/mutations/action.ts
  src/mutations/authentication.ts
  src/mutations/chat.ts
  src/mutations/etherpad.ts
  src/mutations/invitation.ts
  src/mutations/item.ts
  src/mutations/itemCategory.ts
  src/mutations/itemExport.ts
  src/mutations/itemFavorite.ts
  src/mutations/itemFlag.ts
  src/mutations/itemGeolocation.ts
  src/mutations/itemLike.ts
  src/mutations/itemLogin.ts
  src/mutations/itemPublish.ts
  src/mutations/itemTag.ts
  src/mutations/itemValidation.ts
  src/mutations/member.ts
  src/mutations/membership.ts
  src/mutations/mention.ts
  src/mutations/publicProfile.ts
  src/mutations/shortLink.ts
  src/mutations/subscription.ts
  src/queryClient.ts
  src/types.ts
  src/ws/hooks/chat.ts
  src/ws/hooks/item.ts
  src/ws/hooks/membership.ts
  src/ws/hooks/mentions.ts
  test/utils.tsx
  test/wsUtils.tsx
  yarn.lock
Labels: dependencies
