Repository graasp/graasp-query-client, pull requests merged in 2024-03, with the labels that each got.

#669 fix: remove hashing item ids for keys
  package.json
  src/api/item.ts
  src/config/keys.ts
  src/mutations/item.test.ts
  src/mutations/item.ts
  src/utils/item.ts
  yarn.lock
Labels: chore

#676 fix: allow undefined in published info hook
  src/hooks/itemPublish.ts
Labels: chore

#680 fix: add langage on signup
  src/api/authentication.ts
  src/mutations/authentication.ts
Labels: improvement

#693 fix: add public profile return type on api
  package.json
  src/api/publicProfile.ts
  yarn.lock
Labels: improvement

#699 fix: export useQuery to be used in consumers
  src/queryClient.ts
Labels: chore

#708 fix: send name in edit member
  src/api/member.ts
  src/mutations/member.test.ts
Labels: bug :beetle:
