Repository graasp/graasp-query-client, pull requests merged in 2024-09, with the labels that each got.

#912 fix: update current member return type
  src/hooks/mention.ts
  src/item/routes.ts
  src/member/api.ts
  src/mutations/authentication.test.ts
  src/mutations/authentication.ts
Labels: bug :beetle:

#909 chore(main): release 3.22.4
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#919 fix: decode exported filename
  src/api/itemExport.test.ts
  src/api/itemExport.ts
Labels: bug :beetle:

#921 fix: update to remove delete member hook as it is deprecated
  src/member/api.ts
  src/member/mutations.test.ts
  src/member/mutations.ts
  src/member/routes.ts
Labels: chore

#772 feat: password reset request mutations
  package.json
  src/api/authentication.ts
  src/member/mutations.test.ts
  src/mutations/authentication.test.ts
  src/mutations/authentication.ts
  src/routes.ts
  src/routines/authentication.ts
  yarn.lock
Labels: feature

#920 chore(main): release 3.23.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#931 chore(main): release 3.24.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#934 chore(main): release 3.25.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
