Repository graasp/graasp-query-client, pull requests merged in 2024-07, with the labels that each got.

#814 chore(main): release 3.15.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#816 fix: release-please add issue permission
  .github/workflows/release-please.yml
Labels: chore

#815 fix: add email update mutations and re-organize member files
  package.json
  src/api/action.ts
  src/api/index.ts
  src/api/membership.ts
  src/hooks/action.test.ts
  src/hooks/action.ts
  src/hooks/index.ts
  src/hooks/mention.test.ts
  src/member/api.ts
  src/member/hooks.test.ts
  src/member/hooks.ts
  src/member/mutations.test.ts
  src/member/mutations.ts
  src/member/publicProfile/api.ts
  src/member/publicProfile/hooks.test.ts
  src/member/publicProfile/hooks.ts
  src/member/publicProfile/mutations.test.ts
  src/member/publicProfile/mutations.ts
  src/member/publicProfile/routines.ts
  src/member/routes.ts
  src/member/routines.ts
  src/member/subscription/api.ts
  src/member/subscription/hooks.ts
  src/member/subscription/mutations.ts
  src/member/subscription/routines.ts
  src/mutations/index.ts
  src/mutations/membership.test.ts
  src/mutations/membership.ts
  src/mutations/mention.test.ts
  src/routes.ts
  src/routines/index.ts
  src/routines/membership.ts
  yarn.lock
Labels: feature, refactor

#822 chore(main): release 3.15.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#825 fix: do not call logout on delete member as the backend does it automatically
  src/member/api.ts
  src/member/mutations.ts
  src/member/routes.ts
  src/member/routines.ts
Labels: improvement

#827 chore(main): release 3.15.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#831 fix: add invalidation of profile on patch and post
  src/member/publicProfile/mutations.ts
Labels: improvement

#835 chore(main): release 3.16.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#853 chore(main): release 3.17.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#854 fix: update pagination
  package.json
  src/item/accessible/api.ts
  src/item/accessible/hooks.test.ts
  src/item/accessible/hooks.ts
  src/item/routes.ts
  src/keys.ts
  src/types.ts
  yarn.lock
Labels: chore, dependencies

#847 feat: add new hook useMemberStorageFiles
  src/keys.ts
  src/member/api.ts
  src/member/fixtures.ts
  src/member/hooks.test.ts
  src/member/hooks.ts
  src/member/routes.ts
Labels: feature

#855 chore(main): release 3.18.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#858 chore(main): release 3.19.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#861 chore(main): release 3.20.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#824 fix: add member password routes
  src/member/api.ts
  src/member/mutations.test.ts
  src/member/mutations.ts
  src/member/routes.ts
Labels: feature

#866 chore(main): release 3.20.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending
