Repository graasp/graasp-query-client, pull requests merged in 2024-08, with the labels that each got.

#872 chore(main): release 3.20.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#873 chore(main): release 3.20.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#879 chore(main): release 3.21.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#877 feat: add member export data mutation
  src/member/api.ts
  src/member/mutations.test.ts
  src/member/mutations.ts
  src/member/routes.ts
  src/member/routines.ts
Labels: feature

#881 chore(main): release 3.22.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#884 fix: remove deprecated react-test-renderer
  package.json
  src/mutations/itemCategory.test.ts
  src/mutations/itemExport.test.ts
  src/mutations/itemFlag.test.ts
  src/mutations/itemGeolocation.test.ts
  src/mutations/itemLike.test.ts
  src/mutations/itemLogin.test.ts
  src/mutations/itemPublish.test.ts
  src/mutations/itemTag.test.ts
  src/mutations/itemValidation.test.ts
  src/mutations/membership.test.ts
  yarn.lock
Labels: chore, dependencies

#885 chore(main): release 3.22.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#862 fix: update with new sdk for item login changes
  package.json
  src/hooks/chat.test.ts
  src/member/hooks.test.ts
  src/member/publicProfile/mutations.test.ts
  src/mutations/itemLike.test.ts
  src/mutations/itemLogin.test.ts
  src/mutations/itemTag.test.ts
  src/mutations/membership.ts
  src/mutations/mention.test.ts
  src/types.ts
  src/ws/hooks/membership.test.ts
  src/ws/hooks/mentions.test.ts
  test/constants.ts
  yarn.lock
Labels: chore

#888 chore(main): release 3.22.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#890 fix: update eslint for flat config
  .eslintignore
  .eslintrc
  eslint.config.mjs
  package.json
  src/api/csvUserImport.ts
  src/api/embeddedLink.ts
  src/api/etherpad.ts
  src/api/itemFlag.ts
  src/api/search.ts
  src/config/errors.ts
  src/item/accessible/hooks.ts
  src/item/hooks.ts
  src/item/mutations.ts
  src/item/publication/api.ts
  src/routines/csvUserImport.ts
  src/routines/itemExport.ts
  src/routines/itemFlag.ts
  src/routines/thumbnails.ts
  src/ws/hooks/chat.ts
  src/ws/hooks/item.ts
  src/ws/hooks/membership.ts
  src/ws/hooks/mentions.ts
  test/wsUtils.tsx
  yarn.lock
Labels: chore, dependencies

#891 chore(main): release 3.22.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending
