Repository graasp/graasp-query-client, pull requests merged in 2024-01, with the labels that each got.

#557 build: update dependencies
  package.json
  yarn.lock
Labels: build

#580 fix: allow union litterals in aggregate
  src/utils/action.ts
Labels: chore

#594 fix: better understanding of `staleTime` and `cacheTime`
  src/config/constants.ts
  src/hooks/apps.ts
  src/hooks/category.ts
  src/hooks/item.ts
  src/hooks/member.ts
  src/mutations/item.ts
Labels: bug :beetle:, improvement

#604 fix: allow descendents id to be undefined
  src/config/keys.ts
  src/hooks/item.ts
Labels: chore
